"""
Database operations for portfolio management
(PostgreSQL / Neon compatible)
"""

from db_config import get_db_connection, close_connection
from datetime import date
from typing import List, Dict, Optional, Tuple
from psycopg2.extras import RealDictCursor


# ------------------------------------------------------------------
# Categories
# ------------------------------------------------------------------

def get_all_categories() -> List[Dict]:
    connection = get_db_connection()
    if not connection:
        return []

    cursor = None
    try:
        cursor = connection.cursor(cursor_factory=RealDictCursor)
        query = """
            SELECT category_id, category_name, description, is_active, created_at
            FROM investment_category
            WHERE is_active = TRUE
            ORDER BY category_name
        """
        cursor.execute(query)
        return cursor.fetchall()
    except Exception as e:
        print(f"Error fetching categories: {e}")
        return []
    finally:
        if cursor:
            cursor.close()
        close_connection(connection)


def add_category(category_name: str, description: str = "") -> Tuple[bool, str]:
    connection = get_db_connection()
    if not connection:
        return False, "Database connection failed"

    cursor = None
    try:
        cursor = connection.cursor()
        query = """
            INSERT INTO investment_category (category_name, description)
            VALUES (%s, %s)
        """
        cursor.execute(query, (category_name, description))
        connection.commit()
        return True, "Category added successfully"
    except Exception as e:
        connection.rollback()
        if "unique" in str(e).lower():
            return False, f"Category '{category_name}' already exists"
        return False, f"Error adding category: {e}"
    finally:
        if cursor:
            cursor.close()
        close_connection(connection)


# ------------------------------------------------------------------
# Months
# ------------------------------------------------------------------

def get_or_create_month(year: int, month: int, snapshot_date: date) -> Optional[int]:
    connection = get_db_connection()
    if not connection:
        return None

    cursor = None
    try:
        cursor = connection.cursor()

        # Check if month exists
        check_query = """
            SELECT month_id
            FROM portfolio_month
            WHERE year = %s AND month = %s
        """
        cursor.execute(check_query, (year, month))
        row = cursor.fetchone()
        if row:
            return row[0]

        # Insert new month and return ID
        insert_query = """
            INSERT INTO portfolio_month (year, month, snapshot_date)
            VALUES (%s, %s, %s)
            RETURNING month_id
        """
        cursor.execute(insert_query, (year, month, snapshot_date))
        month_id = cursor.fetchone()[0]
        connection.commit()
        return month_id

    except Exception as e:
        connection.rollback()
        print(f"Error getting/creating month: {e}")
        return None
    finally:
        if cursor:
            cursor.close()
        close_connection(connection)


def get_all_months() -> List[Dict]:
    connection = get_db_connection()
    if not connection:
        return []

    cursor = None
    try:
        cursor = connection.cursor(cursor_factory=RealDictCursor)
        query = """
            SELECT month_id, year, month, snapshot_date
            FROM portfolio_month
            ORDER BY year DESC, month DESC
        """
        cursor.execute(query)
        return cursor.fetchall()
    except Exception as e:
        print(f"Error fetching months: {e}")
        return []
    finally:
        if cursor:
            cursor.close()
        close_connection(connection)


# ------------------------------------------------------------------
# Portfolio Values
# ------------------------------------------------------------------

def save_portfolio_value(
    month_id: int,
    category_id: int,
    amount: float
) -> Tuple[bool, str]:
    connection = get_db_connection()
    if not connection:
        return False, "Database connection failed"

    cursor = None
    try:
        cursor = connection.cursor()
        # Use ON CONFLICT to handle updates when the same month_id and category_id exist
        # value_id is auto-generated by PostgreSQL SERIAL, so we don't specify it
        query = """
            INSERT INTO portfolio_value (month_id, category_id, amount)
            VALUES (%s, %s, %s)
            ON CONFLICT (month_id, category_id)
            DO UPDATE SET
                amount = EXCLUDED.amount,
                updated_at = CURRENT_TIMESTAMP
        """
        cursor.execute(query, (month_id, category_id, amount))
        connection.commit()
        return True, "Portfolio value saved successfully"
    except Exception as e:
        connection.rollback()
        error_msg = str(e)
        # Provide more helpful error message for sequence issues
        if "duplicate key" in error_msg.lower() and "pkey" in error_msg.lower():
            return False, f"Error saving portfolio value: duplicate key value violates unique constraint. Please run 'python fix_sequence.py' to fix the database sequence."
        return False, f"Error saving portfolio value: {e}"
    finally:
        if cursor:
            cursor.close()
        close_connection(connection)


def get_portfolio_data(
    year: Optional[int] = None,
    month: Optional[int] = None
) -> List[Dict]:
    connection = get_db_connection()
    if not connection:
        return []

    cursor = None
    try:
        cursor = connection.cursor(cursor_factory=RealDictCursor)
        query = """
            SELECT
                pm.year,
                pm.month,
                pm.snapshot_date,
                ic.category_name,
                pv.amount,
                pv.updated_at
            FROM portfolio_value pv
            JOIN portfolio_month pm ON pv.month_id = pm.month_id
            JOIN investment_category ic ON pv.category_id = ic.category_id
            WHERE 1 = 1
        """
        params = []

        if year is not None:
            query += " AND pm.year = %s"
            params.append(year)

        if month is not None:
            query += " AND pm.month = %s"
            params.append(month)

        query += " ORDER BY pm.year DESC, pm.month DESC, ic.category_name"

        cursor.execute(query, params)
        return cursor.fetchall()
    except Exception as e:
        print(f"Error fetching portfolio data: {e}")
        return []
    finally:
        if cursor:
            cursor.close()
        close_connection(connection)


def get_monthly_summary(year: int, month: int) -> Dict:
    connection = get_db_connection()
    if not connection:
        return {}

    cursor = None
    try:
        cursor = connection.cursor(cursor_factory=RealDictCursor)
        query = """
            SELECT
                pm.year,
                pm.month,
                pm.snapshot_date,
                COUNT(pv.value_id) AS category_count,
                COALESCE(SUM(pv.amount), 0) AS total_value
            FROM portfolio_month pm
            LEFT JOIN portfolio_value pv ON pm.month_id = pv.month_id
            WHERE pm.year = %s AND pm.month = %s
            GROUP BY pm.month_id, pm.year, pm.month, pm.snapshot_date
        """
        cursor.execute(query, (year, month))
        row = cursor.fetchone()
        return row if row else {}
    except Exception as e:
        print(f"Error fetching monthly summary: {e}")
        return {}
    finally:
        if cursor:
            cursor.close()
        close_connection(connection)


# ------------------------------------------------------------------
# Delete / Update
# ------------------------------------------------------------------

def delete_category(category_id: int) -> Tuple[bool, str]:
    connection = get_db_connection()
    if not connection:
        return False, "Database connection failed"

    cursor = None
    try:
        cursor = connection.cursor()
        query = """
            UPDATE investment_category
            SET is_active = FALSE
            WHERE category_id = %s
        """
        cursor.execute(query, (category_id,))
        connection.commit()
        return True, "Category deleted successfully"
    except Exception as e:
        connection.rollback()
        return False, f"Error deleting category: {e}"
    finally:
        if cursor:
            cursor.close()
        close_connection(connection)


def get_portfolio_value_history(num_months: int = 6) -> List[Dict]:
    """
    Get historical portfolio values aggregated by month
    Returns the most recent N months with total portfolio values
    """
    connection = get_db_connection()
    if not connection:
        return []

    cursor = None
    try:
        cursor = connection.cursor(cursor_factory=RealDictCursor)
        query = """
            SELECT
                pm.year,
                pm.month,
                pm.snapshot_date,
                COALESCE(SUM(pv.amount), 0) AS total_value
            FROM portfolio_month pm
            LEFT JOIN portfolio_value pv ON pm.month_id = pv.month_id
            GROUP BY pm.month_id, pm.year, pm.month, pm.snapshot_date
            ORDER BY pm.year DESC, pm.month DESC
            LIMIT %s
        """
        cursor.execute(query, (num_months,))
        results = cursor.fetchall()
        # Return in chronological order (oldest first) for chart display
        return list(reversed(results))
    except Exception as e:
        print(f"Error fetching portfolio value history: {e}")
        return []
    finally:
        if cursor:
            cursor.close()
        close_connection(connection)
